[package]
org = "nuvindu"
name = "pipe"
version = "@toml.version@"
authors = ["Nuvindu"]
keywords = ["pipe"]
repository = "https://github.com/Nuvindu/module-pipe"
license = ["Apache-2.0"]
distribution = "2201.0.1"

[[platform.java11.dependency]]
path = "../native/build/libs/pipe-native-@project.version@.jar"
