[package]
org = "nuvindu_dias"
name = "pipe"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["pipe"]
repository = "https://github.com/Nuvindu/module-pipe"
license = ["Apache-2.0"]
distribution = "2201.0.1"
