[package]
org = "nuvindu"
name = "pipe"
version = "1.0.1"
authors = ["Nuvindu"]
keywords = ["pipe"]
repository = "https://github.com/Nuvindu/module-pipe"
license = ["Apache-2.0"]
distribution = "2201.2.0"
icon = "icon.png"

[[platform.java11.dependency]]
path = "../native/build/libs/pipe-native-1.0.1-SNAPSHOT.jar"
