[package]
org = "nuvindu"
name = "pipe"
version = "0.1.6"
authors = ["Nuvindu"]
keywords = ["pipe"]
repository = "https://github.com/Nuvindu/module-pipe"
license = ["Apache-2.0"]
distribution = "2201.0.1"
icon = "icon.png"

[[platform.java11.dependency]]
path = "../native/build/libs/pipe-native-0.1.6-SNAPSHOT.jar"
