[package]
org = "nuvindu"
name = "covid_report"
version = "0.1.0"
distribution = "2201.0.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "nuvindu"
name = "pipe"
version = "0.1.0"
repository = "local"
